# Data Cleaning & Data Manipulation

In [1]:
import pandas as pd
import numpy as np

In [2]:
data1 = np.random.randn(10,3)
data2 = np.random.randn(7,3)

In [3]:
df1 = pd.DataFrame(data1, columns=["Col1", "Col2", "Col3"])
df2 = pd.DataFrame(data2, columns=["Col1", "Col2", "Col3"])

In [4]:
df1

       Col1      Col2      Col3
0 -0.282455  0.933882 -0.940976
1 -1.335738  0.144776  0.573165
2  0.644326  0.078392 -0.581925
3 -0.813927  1.531292 -0.576625
4  1.206105 -0.190608 -1.040967
5  0.841636 -0.654613  0.623576
6 -0.134767 -0.406992 -0.307459
7 -0.047945  1.199079 -0.920376
8 -2.203601  0.725854  0.425721
9  0.656195  1.350195 -1.096695

In [5]:
df2

       Col1      Col2      Col3
0 -0.220045 -0.101796 -0.015215
1  0.410903  0.943433 -0.451294
2  0.793187  0.420557  0.311142
3 -0.658115 -0.952783 -1.100947
4  1.386487 -0.589618  1.374284
5 -1.192486  0.141447  0.818705
6  0.767653  2.143932 -0.574193

In [ ]:
df3 = df1 + df2
df3 = df[1] + df[2]

In [6]:
df3 = pd.concat([df1,df2], ignore_index=True)

In [7]:
df3

        Col1      Col2      Col3
0  -0.282455  0.933882 -0.940976
1  -1.335738  0.144776  0.573165
2   0.644326  0.078392 -0.581925
3  -0.813927  1.531292 -0.576625
4   1.206105 -0.190608 -1.040967
5   0.841636 -0.654613  0.623576
6  -0.134767 -0.406992 -0.307459
7  -0.047945  1.199079 -0.920376
8  -2.203601  0.725854  0.425721
9   0.656195  1.350195 -1.096695
10 -0.220045 -0.101796 -0.015215
11  0.410903  0.943433 -0.451294
12  0.793187  0.420557  0.311142
13 -0.658115 -0.952783 -1.100947
14  1.386487 -0.589618  1.374284
15 -1.192486  0.141447  0.818705
16  0.767653  2.143932 -0.574193

In [8]:
for i in df3.Col3:
  print(i)

-0.9409762863006191
0.5731653383077833
-0.5819249832917103
-0.5766249135381487
-1.0409670336872556
0.623576296300973
-0.30745882071686
-0.9203764292034297
0.42572129256381586
-1.0966952749340586
-0.01521526215822475
-0.4512939173981378
0.3111416875723937
-1.100946891496513
1.3742840093274449
0.8187046841214114
-0.5741933743903356

* iteritems -> Iterate each column for Key, Value Pair

In [10]:
# For interating over columns
for key, value in df3.items():
    print(key, value)

Col1 0    -0.282455
1    -1.335738
2     0.644326
3    -0.813927
4     1.206105
5     0.841636
6    -0.134767
7    -0.047945
8    -2.203601
9     0.656195
10   -0.220045
11    0.410903
12    0.793187
13   -0.658115
14    1.386487
15   -1.192486
16    0.767653
Name: Col1, dtype: float64
Col2 0     0.933882
1     0.144776
2     0.078392
3     1.531292
4    -0.190608
5    -0.654613
6    -0.406992
7     1.199079
8     0.725854
9     1.350195
10   -0.101796
11    0.943433
12    0.420557
13   -0.952783
14   -0.589618
15    0.141447
16    2.143932
Name: Col2, dtype: float64
Col3 0    -0.940976
1     0.573165
2    -0.581925
3    -0.576625
4    -1.040967
5     0.623576
6    -0.307459
7    -0.920376
8     0.425721
9    -1.096695
10   -0.015215
11   -0.451294
12    0.311142
13   -1.100947
14    1.374284
15    0.818705
16   -0.574193
Name: Col3, dtype: float64

* iterrows()

In [11]:
# For interating over rows
for index,row in df3.iterrows():
  print(index, row)

0 Col1   -0.282455
Col2    0.933882
Col3   -0.940976
Name: 0, dtype: float64
1 Col1   -1.335738
Col2    0.144776
Col3    0.573165
Name: 1, dtype: float64
2 Col1    0.644326
Col2    0.078392
Col3   -0.581925
Name: 2, dtype: float64
3 Col1   -0.813927
Col2    1.531292
Col3   -0.576625
Name: 3, dtype: float64
4 Col1    1.206105
Col2   -0.190608
Col3   -1.040967
Name: 4, dtype: float64
5 Col1    0.841636
Col2   -0.654613
Col3    0.623576
Name: 5, dtype: float64
6 Col1   -0.134767
Col2   -0.406992
Col3   -0.307459
Name: 6, dtype: float64
7 Col1   -0.047945
Col2    1.199079
Col3   -0.920376
Name: 7, dtype: float64
8 Col1   -2.203601
Col2    0.725854
Col3    0.425721
Name: 8, dtype: float64
9 Col1    0.656195
Col2    1.350195
Col3   -1.096695
Name: 9, dtype: float64
10 Col1   -0.220045
Col2   -0.101796
Col3   -0.015215
Name: 10, dtype: float64
11 Col1    0.410903
Col2    0.943433
Col3   -0.451294
Name: 11, dtype: float64
12 Col1    0.793187
Col2    0.420557
Col3    0.311142
Name: 12, dtype: float64
13 Col1   -0.658115
Col2   -0.952783
Col3   -1.100947
Name: 13, dtype: float64
14 Col1    1.386487
Col2   -0.589618
Col3    1.374284
Name: 14, dtype: float64
15 Col1   -1.192486
Col2    0.141447
Col3    0.818705
Name: 15, dtype: float64
16 Col1    0.767653
Col2    2.143932
Col3   -0.574193
Name: 16, dtype: float64

* Sort - sort_index()
* Here indices will be arranged in accesending order

In [12]:
unsorted_df = pd.DataFrame(np.random.randn(10,3), 
                           index = [5,7,3,9,2,1,9,11,21,4],
                           columns = ['Col1', 'Col2', 'Col3'])

In [13]:
unsorted_df

        Col1      Col2      Col3
5  -1.081973 -1.014050  0.347884
7  -0.575653  1.351084 -1.179921
3  -1.608354  0.403431 -1.351842
9  -0.475155 -0.545053 -0.200241
2   1.350505  0.917365 -0.930483
1  -0.186917  0.780693  0.526021
9   1.450916  0.876312 -0.708794
11  0.038535  0.708774  0.489814
21 -1.948005 -1.057107 -0.171984
4  -0.150979 -0.328353 -1.182602

In [14]:
unsorted_df.sort_index()

        Col1      Col2      Col3
1  -0.186917  0.780693  0.526021
2   1.350505  0.917365 -0.930483
3  -1.608354  0.403431 -1.351842
4  -0.150979 -0.328353 -1.182602
5  -1.081973 -1.014050  0.347884
7  -0.575653  1.351084 -1.179921
9  -0.475155 -0.545053 -0.200241
9   1.450916  0.876312 -0.708794
11  0.038535  0.708774  0.489814
21 -1.948005 -1.057107 -0.171984

In [15]:
unsorted_df.sort_index(ascending=False)

        Col1      Col2      Col3
21 -1.948005 -1.057107 -0.171984
11  0.038535  0.708774  0.489814
9  -0.475155 -0.545053 -0.200241
9   1.450916  0.876312 -0.708794
7  -0.575653  1.351084 -1.179921
5  -1.081973 -1.014050  0.347884
4  -0.150979 -0.328353 -1.182602
3  -1.608354  0.403431 -1.351842
2   1.350505  0.917365 -0.930483
1  -0.186917  0.780693  0.526021

In [16]:
unsorted_df.sort_index(axis=1) # To sort columns we will use axis = 1 and to sort rows we will use axis = 1

        Col1      Col2      Col3
5  -1.081973 -1.014050  0.347884
7  -0.575653  1.351084 -1.179921
3  -1.608354  0.403431 -1.351842
9  -0.475155 -0.545053 -0.200241
2   1.350505  0.917365 -0.930483
1  -0.186917  0.780693  0.526021
9   1.450916  0.876312 -0.708794
11  0.038535  0.708774  0.489814
21 -1.948005 -1.057107 -0.171984
4  -0.150979 -0.328353 -1.182602

In [17]:
unsorted_df.sort_index(axis=1, ascending=False)

        Col3      Col2      Col1
5   0.347884 -1.014050 -1.081973
7  -1.179921  1.351084 -0.575653
3  -1.351842  0.403431 -1.608354
9  -0.200241 -0.545053 -0.475155
2  -0.930483  0.917365  1.350505
1   0.526021  0.780693 -0.186917
9  -0.708794  0.876312  1.450916
11  0.489814  0.708774  0.038535
21 -0.171984 -1.057107 -1.948005
4  -1.182602 -0.328353 -0.150979

In [18]:
[6,5,8,2,5,9,2,1].sort() #-> Timsort

* sort_values()

In [19]:
df = pd.DataFrame({"Apples":[50,95, 105,75],"Grapes":[110,45,99,0]})

In [20]:
df

   Apples  Grapes
0      50     110
1      95      45
2     105      99
3      75       0

In [21]:
df.sort_values(by=['Apples', 'Grapes'])

   Apples  Grapes
0      50     110
3      75       0
1      95      45
2     105      99

# Quicksort
* Description: Quicksort is a divide-and-conquer algorithm. It works by selecting a 'pivot' element from the array and partitioning the other elements into two sub-arrays, according to whether they are less than or greater than the pivot.
* Time Complexity:
* Average: O(n log n)
* Worst: O(n^2) (though this is rare with good pivot selection)
* Space Complexity: O(log n) due to recursion stack
* Stability: Not stable (relative order of equal sort items might change)
* Usage: Good general-purpose sort that is fast on average.
# Mergesort
* Description: Mergesort is also a divide-and-conquer algorithm. It divides the array into two halves, recursively sorts them, and then merges the sorted halves.
* Time Complexity:
* Average and Worst: O(n log n)
* Space Complexity: O(n) due to auxiliary arrays used in merging
* Stability: Stable (relative order of equal sort items is preserved)
* Usage: Preferred when stability is required.
# Heapsort
* Description: Heapsort transforms the array into a heap, then repeatedly extracts the maximum element from the heap and rebuilds the heap until all elements are sorted.
* Time Complexity:
* Average and Worst: O(n log n)
* Space Complexity: O(1) (in-place sorting)
* Stability: Not stable
* Usage: Useful when constant space usage is needed.

In [24]:
df.sort_values(by=['Apples', 'Grapes'],kind='mergesort')
# 1. Quicksort
# 2. Mergesort
# 3. Heapsort

   Apples  Grapes
0      50     110
3      75       0
1      95      45
2     105      99

* Stats - Advanced

In [25]:
df3

        Col1      Col2      Col3
0  -0.282455  0.933882 -0.940976
1  -1.335738  0.144776  0.573165
2   0.644326  0.078392 -0.581925
3  -0.813927  1.531292 -0.576625
4   1.206105 -0.190608 -1.040967
5   0.841636 -0.654613  0.623576
6  -0.134767 -0.406992 -0.307459
7  -0.047945  1.199079 -0.920376
8  -2.203601  0.725854  0.425721
9   0.656195  1.350195 -1.096695
10 -0.220045 -0.101796 -0.015215
11  0.410903  0.943433 -0.451294
12  0.793187  0.420557  0.311142
13 -0.658115 -0.952783 -1.100947
14  1.386487 -0.589618  1.374284
15 -1.192486  0.141447  0.818705
16  0.767653  2.143932 -0.574193

In [26]:
df4 = df3.drop([8,9,10,11,12,13,14,15,16])

In [28]:
df3

        Col1      Col2      Col3
0  -0.282455  0.933882 -0.940976
1  -1.335738  0.144776  0.573165
2   0.644326  0.078392 -0.581925
3  -0.813927  1.531292 -0.576625
4   1.206105 -0.190608 -1.040967
5   0.841636 -0.654613  0.623576
6  -0.134767 -0.406992 -0.307459
7  -0.047945  1.199079 -0.920376
8  -2.203601  0.725854  0.425721
9   0.656195  1.350195 -1.096695
10 -0.220045 -0.101796 -0.015215
11  0.410903  0.943433 -0.451294
12  0.793187  0.420557  0.311142
13 -0.658115 -0.952783 -1.100947
14  1.386487 -0.589618  1.374284
15 -1.192486  0.141447  0.818705
16  0.767653  2.143932 -0.574193

In [29]:
df4

       Col1      Col2      Col3
0 -0.282455  0.933882 -0.940976
1 -1.335738  0.144776  0.573165
2  0.644326  0.078392 -0.581925
3 -0.813927  1.531292 -0.576625
4  1.206105 -0.190608 -1.040967
5  0.841636 -0.654613  0.623576
6 -0.134767 -0.406992 -0.307459
7 -0.047945  1.199079 -0.920376

* Covariance -> cov()

In [30]:
df4.Col2

0    0.933882
1    0.144776
2    0.078392
3    1.531292
4   -0.190608
5   -0.654613
6   -0.406992
7    1.199079
Name: Col2, dtype: float64

In [31]:
df4['Col2']

0    0.933882
1    0.144776
2    0.078392
3    1.531292
4   -0.190608
5   -0.654613
6   -0.406992
7    1.199079
Name: Col2, dtype: float64

In [32]:
df4.Col2.cov(df4['Col3'])

-0.26684441672029685

In [33]:
df4.cov

<bound method DataFrame.cov of        Col1      Col2      Col3
0 -0.282455  0.933882 -0.940976
1 -1.335738  0.144776  0.573165
2  0.644326  0.078392 -0.581925
3 -0.813927  1.531292 -0.576625
4  1.206105 -0.190608 -1.040967
5  0.841636 -0.654613  0.623576
6 -0.134767 -0.406992 -0.307459
7 -0.047945  1.199079 -0.920376>

* Correlation - corr

In [34]:
df4['Col2'].corr(df4['Col3'])

-0.5080274740534441

In [35]:
df4.corr

<bound method DataFrame.corr of        Col1      Col2      Col3
0 -0.282455  0.933882 -0.940976
1 -1.335738  0.144776  0.573165
2  0.644326  0.078392 -0.581925
3 -0.813927  1.531292 -0.576625
4  1.206105 -0.190608 -1.040967
5  0.841636 -0.654613  0.623576
6 -0.134767 -0.406992 -0.307459
7 -0.047945  1.199079 -0.920376>

# Data Cleaning

In [36]:
df = pd.DataFrame(np.random.randn(5,3),
                index = ["A", "C", "E", "F", "G"],
                columns = ["Col1", "Col2", "Col3"])

In [37]:
df

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
C  1.248693 -0.036142 -0.654065
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095

In [38]:
df = df.reindex(["A", "B", "C", "D", "E", "F", "G", "H"])

In [39]:
df

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

* isnull()

In [40]:
df.isnull()

    Col1   Col2   Col3
A  False  False  False
B   True   True   True
C  False  False  False
D   True   True   True
E  False  False  False
F  False  False  False
G  False  False  False
H   True   True   True

In [41]:
df.isna() # exactly same as isnull

    Col1   Col2   Col3
A  False  False  False
B   True   True   True
C  False  False  False
D   True   True   True
E  False  False  False
F  False  False  False
G  False  False  False
H   True   True   True

In [42]:
df.notnull() # all false will become true and vice veesa

    Col1   Col2   Col3
A   True   True   True
B  False  False  False
C   True   True   True
D  False  False  False
E   True   True   True
F   True   True   True
G   True   True   True
H  False  False  False

In [44]:
df.isnull().sum(1) # It will give total number of null values in each cols

A    0
B    3
C    0
D    3
E    0
F    0
G    0
H    3
dtype: int64

In [45]:
df.isnull().sum().sum() # It will add all the cols and give total no. of null columns

9

In [46]:
df.count() # It will show no. of not null values

Col1    5
Col2    5
Col3    5
dtype: int64

In [47]:
df['Col1'].isnull()

A    False
B     True
C    False
D     True
E    False
F    False
G    False
H     True
Name: Col1, dtype: bool

In [48]:
df.loc["G"].isnull()

Col1    False
Col2    False
Col3    False
Name: G, dtype: bool

* isna()

In [49]:
df.isna()

    Col1   Col2   Col3
A  False  False  False
B   True   True   True
C  False  False  False
D   True   True   True
E  False  False  False
F  False  False  False
G  False  False  False
H   True   True   True

In [50]:
df.isna().dtypes

Col1    bool
Col2    bool
Col3    bool
dtype: object

In [51]:
df.dtypes

Col1    float64
Col2    float64
Col3    float64
dtype: object

* notnull()

In [52]:
df.notnull()

    Col1   Col2   Col3
A   True   True   True
B  False  False  False
C   True   True   True
D  False  False  False
E   True   True   True
F   True   True   True
G   True   True   True
H  False  False  False

In [53]:
df.notnull().sum(1)

A    3
B    0
C    3
D    0
E    3
F    3
G    3
H    0
dtype: int64

In [54]:
df.count()

Col1    5
Col2    5
Col3    5
dtype: int64

* Clean Missing (NaN) Values

In [55]:
df

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

* fillna() -> It will fill the null values

In [56]:
df.fillna(10)

        Col1       Col2       Col3
A  -0.920224  -1.211762   2.236868
B  10.000000  10.000000  10.000000
C   1.248693  -0.036142  -0.654065
D  10.000000  10.000000  10.000000
E   0.877121  -0.085387  -1.024850
F   0.320942   0.261678   1.507580
G  -0.501715  -0.399513  -1.150095
H  10.000000  10.000000  10.000000

In [ ]:
# Forward Method - pad/ffill
# Backward Method - bfill/backfill

In [57]:
df

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

In [64]:
df.fillna(method='pad')

C:\Users\Asus\AppData\Local\Temp\ipykernel_13948\2128539113.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B -0.920224 -1.211762  2.236868
C  1.248693 -0.036142 -0.654065
D  1.248693 -0.036142 -0.654065
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H -0.501715 -0.399513 -1.150095

In [62]:
df.fillna(method='pad',axis=1)

C:\Users\Asus\AppData\Local\Temp\ipykernel_13948\297991498.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad',axis=1)

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

In [65]:
df.fillna(method='bfill')

C:\Users\Asus\AppData\Local\Temp\ipykernel_13948\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B  1.248693 -0.036142 -0.654065
C  1.248693 -0.036142 -0.654065
D  0.877121 -0.085387 -1.024850
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

* dropna() -> means droping the NaN values. This will also reduce the accuracy of table so suggestion is not to use it for small dataset

In [66]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [A, B, C, D, E, F, G, H]

* Replacing values - replace()

In [69]:
df

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

In [71]:
df.replace({-0.92022:100.0, 2.479047:200.0})

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

In [72]:
df.replace({50:90, 99:245})

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

In [73]:
df

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

# IMP NOTE:
Never use drop in data anywhere else in interviews you will be directly get rejected
Instead use replace function to replace the data

In [ ]:
df.Apples.loc[2] = 500

In [ ]:
df

   Apples  Grapes
0      50     110
1      95      45
2     500      99
3      75       0

In [ ]:
df.Grapes.loc[2] = 299
df.loc[____, ___]

In [76]:
df

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

In [ ]:
df.Apples.loc[3] = 50

In [77]:
df

       Col1      Col2      Col3
A -0.920224 -1.211762  2.236868
B       NaN       NaN       NaN
C  1.248693 -0.036142 -0.654065
D       NaN       NaN       NaN
E  0.877121 -0.085387 -1.024850
F  0.320942  0.261678  1.507580
G -0.501715 -0.399513 -1.150095
H       NaN       NaN       NaN

# Handle Duplicates Values

* Check the cuplicate values - duplicated()

In [ ]:
df.duplicated(subset=['Apples']) # It will show index of duplicated value from value which comes earlier

* Remove duplicate values -> drop_duplicates()

In [ ]:
df

   Apples  Grapes
0      50     110
1      95      45
2     500     299
3      50       0

In [ ]:
df.drop_duplicates(subset=['Apples'])

   Apples  Grapes
0      50     110
1      95      45
2     500     299

Now Let's see how to Import a dataset

In [81]:
data = "https://raw.githubusercontent.com/ShapeAI/Python-for-Data-Science-/master/stocks.csv"
df = pd.read_csv(data)
# we can also do df = pd.read_csv("https://raw.githubusercontent.com/ShapeAI/Python-for-Data-Science-/master/stocks.csv")

In [82]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2004-08-19,49.676899,51.693783,47.669952,49.845802,49.845802,44994500
1,2004-08-20,50.178635,54.187561,49.925285,53.805050,53.805050,23005800
2,2004-08-23,55.017166,56.373344,54.172661,54.346527,54.346527,18393200
3,2004-08-24,55.260582,55.439419,51.450363,52.096165,52.096165,15361800
4,2004-08-25,52.140873,53.651051,51.604362,52.657513,52.657513,9257400
...,...,...,...,...,...,...,...
3308,2017-10-09,980.000000,985.424988,976.109985,977.000000,977.000000,891400
3309,2017-10-10,980.000000,981.570007,966.080017,972.599976,972.599976,968400
3310,2017-10-11,973.719971,990.710022,972.250000,989.250000,989.250000,1693300
3311,2017-10-12,987.450012,994.119995,985.000000,987.830017,987.830017,1262400
3312,2017-10-13,992.000000,997.210022,989.000000,989.679993,989.679993,1157700

Now Let's see how to Export a dataset

In [ ]:
df.to_csv("name_of_the_new_file.csv","location")

In [83]:
df['Open'].nunique()

3208

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3313 entries, 0 to 3312
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       3313 non-null   object
 1   Open       3313 non-null   float64
 2   High       3313 non-null   float64
 3   Low        3313 non-null   float64
 4   Close      3313 non-null   float64
 5   Adj Close  3313 non-null   float64
 6   Volume     3313 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 181.3+ KB

In [ ]:
type(df)
String
GroupBY

pandas.core.frame.DataFrame

In [ ]:
df = pd.read_csv('population_india_census2011.csv')

In [ ]:
df

    Sno  ... Gender Ratio
0     1  ...          912
1     2  ...          929
2     3  ...          918
3     4  ...          953
4     5  ...          931
5     6  ...          996
6     7  ...          928
7     8  ...          973
8     9  ...          919
9    10  ...          993
10   11  ...          979
11   12  ...          988
12   13  ...         1084
13   14  ...          948
14   15  ...          954
15   16  ...          895
16   17  ...          991
17   18  ...          879
18   19  ...          963
19   20  ...          972
20   21  ...          960
21   22  ...          989
22   23  ...          992
23   24  ...          931
24   25  ...          973
25   26  ...          938
26   27  ...          976
27   28  ...          890
28   29  ...          868
29   30  ...          890
30   31  ...         1037
31   32  ...          818
32   33  ...          711
33   34  ...          876
34   35  ...          853
35   36  ...          946

[36 rows x 8 columns]

In [ ]:
virtualenv venv
source venv/bin/activate
cd venv/bin/ -> activate
deactivate

In [ ]:
df.loc[,]